import { Inter, Poppins, Libre_Baskerville } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"],
weight: ['400', '700'] });
const libre_baskervile = Libre_Baskerville({ subsets: ["latin"],
weight: ['400', '700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <nav className="m-auto flex justify-center gap-4 py-8">
        <Link className="text-blue-500" href="/">Hjem</Link>
        <Link href="report">report</Link>
        </nav>
        {children}
        </body>
    </html>
  );
}
